syndesisio/syndesis-rest

.editorconfig
circle.yml
pom.xml
readme.md
runtime/pom.xml
runtime/src/docs/asciidoc/index.adoc
runtime/src/main/java/com/redhat/ipaas/rest/ComponentGroups.java
runtime/src/main/java/com/redhat/ipaas/rest/Components.java
runtime/src/main/java/com/redhat/ipaas/rest/Connections.java
runtime/src/main/java/com/redhat/ipaas/rest/IntegrationPatterns.java
runtime/src/main/java/com/redhat/ipaas/rest/IntegrationTemplates.java
runtime/src/main/java/com/redhat/ipaas/rest/Integrations.java
runtime/src/main/java/com/redhat/ipaas/rest/Organizations.java
runtime/src/main/java/com/redhat/ipaas/rest/Permissions.java
runtime/src/main/java/com/redhat/ipaas/rest/Roles.java
runtime/src/main/java/com/redhat/ipaas/rest/Users.java
runtime/src/main/java/com/redhat/ipaas/rest/VersionEndpoint.java
runtime/src/main/java/com/redhat/ipaas/runtime/Main.java

When run with `java -jar target/swarm-runtime.jar`, static HTML docs are served
from http://localhost:8080. Haven't figured out how to get those embedded in dev
mode, but that's less important anyway.

Add generation of static HTML docs served from API server

---

api/src/main/java/com/redhat/ipaas/api/v1/model/WithName.java
runtime/src/main/java/com/redhat/ipaas/rest/ComponentGroups.java
runtime/src/main/java/com/redhat/ipaas/rest/Components.java
runtime/src/main/java/com/redhat/ipaas/rest/Connections.java
runtime/src/main/java/com/redhat/ipaas/rest/DataManager.java
runtime/src/main/java/com/redhat/ipaas/rest/IntegrationPatterns.java
runtime/src/main/java/com/redhat/ipaas/rest/IntegrationTemplates.java
runtime/src/main/java/com/redhat/ipaas/rest/Integrations.java
runtime/src/main/java/com/redhat/ipaas/rest/Permissions.java
runtime/src/main/java/com/redhat/ipaas/rest/Roles.java
runtime/src/main/java/com/redhat/ipaas/rest/SortOptionsFromQueryParams.java
runtime/src/main/java/com/redhat/ipaas/rest/Users.java
runtime/src/main/java/com/redhat/ipaas/rest/util/ReflectiveSorter.java
runtime/src/main/java/com/redhat/ipaas/rest/util/SortOptions.java
runtime/src/main/java/com/redhat/ipaas/runtime/Main.java
runtime/src/test/java/com/redhat/ipaas/rest/DataManagerTest.java
runtime/src/test/java/com/redhat/ipaas/rest/util/ReflectiveSortComparatorTest.java
runtime/src/test/java/com/redhat/ipaas/rest/util/ReflectiveSorterTest.java

You can use the following query parameters:
* "sort" to specify on which field to support. Supported are currently integer and string fields.
* "direction" can be "asc" or "desc" dependening on which direction to sort. Default is "asc"
Still open: Proper Swagger annotation which is probably done via a "Parameters Definition Object" (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameters-definitions-object) so that it doesnt not have to repeated all over all.
Also it would be nice to sort on multiple levels (by providing multiple sort fields) and also on deeper values by allowing a path expression for the field. But thats probably over the top for now ;-)
Interesting also: The DataManager.fetch(...) method can take a list of transformers (like the …

Add support for sorting for all list operations

---

runtime/src/main/java/com/redhat/ipaas/rest/BaseHandler.java
runtime/src/main/java/com/redhat/ipaas/rest/ComponentGroups.java
runtime/src/main/java/com/redhat/ipaas/rest/Components.java
runtime/src/main/java/com/redhat/ipaas/rest/Connections.java
runtime/src/main/java/com/redhat/ipaas/rest/Creator.java
runtime/src/main/java/com/redhat/ipaas/rest/Deleter.java
runtime/src/main/java/com/redhat/ipaas/rest/Getter.java
runtime/src/main/java/com/redhat/ipaas/rest/IntegrationPatterns.java
runtime/src/main/java/com/redhat/ipaas/rest/IntegrationTemplates.java
runtime/src/main/java/com/redhat/ipaas/rest/Integrations.java
runtime/src/main/java/com/redhat/ipaas/rest/Lister.java
runtime/src/main/java/com/redhat/ipaas/rest/Organizations.java
runtime/src/main/java/com/redhat/ipaas/rest/Permissions.java
runtime/src/main/java/com/redhat/ipaas/rest/Resource.java
runtime/src/main/java/com/redhat/ipaas/rest/Roles.java
runtime/src/main/java/com/redhat/ipaas/rest/Updater.java
runtime/src/main/java/com/redhat/ipaas/rest/WithDataManager.java

Would love feedback on this approach to ensure a consistent API with little repeated code. The approach uses default methods on interfaces to act like traits to compose functionality in the REST API layer.
One outstanding problems is Swagger descriptions: generics don't play nicely with swagger and description strings in annotations need to be constants. I'm thinking of using annotation processing to generate implementations of these interfaces, supplying annotations on the managed model classes. These generated classes would of course not be editable, but we can also generate a subclassed implementation where we can extend or override as needed.
I've tested this with the iPaaS UI & it all works fine :)

WIP: Composable REST API

---

api/src/main/java/com/redhat/ipaas/api/v1/model/ListResult.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/DataManager.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/JacksonContextResolver.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/Lister.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/PaginationOptionsFromQueryParams.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/util/PaginationFilter.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/util/PaginationOptions.java
api/src/test/java/com/redhat/ipaas/api/v1/rest/DataManagerTest.java
api/src/test/java/com/redhat/ipaas/api/v1/rest/util/PaginationFilterTest.java

This also serializes empty collections as well to be more explicit for clients.
@kahboom @gashcrumb This is place for when you look at doing virtual scrolling stuff, whenever that is.

Add pagination options to API via query_params

---

api/pom.xml
api/src/main/java/com/redhat/ipaas/api/v1/model/Integration.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/BaseHandler.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/DataAccessObject.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/DataAccessObjectRegistry.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/DataManager.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/IntegrationDAO.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/Integrations.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/KubernetesClientProducer.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/ModelData.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/ObjectMapperProducer.java
api/src/main/resources/com/redhat/ipaas/api/v1/deployment.json
api/src/test/java/com/redhat/ipaas/api/v1/rest/DataManagerTest.java
api/src/test/java/com/redhat/ipaas/api/v1/rest/InfinispanCache.java
api/src/test/java/com/redhat/ipaas/api/v1/rest/ReadApiClientDataTest.java
pom.xml

This is work in progress, which means that you can review, provide feedback, but its not to be merged yet.
The end goal is to create a back-end for Integrations. 
At this point an integration can be a configmap or secret, with a special kind of label that indicates its an integration. The back end can be a simple cdi bean that talks to the openshift rest api in order to read/write the config maps. 
To do so we need to make some changes, like being able to hook back-end service to the data manager, and also integrate with the cache.
So far the pull request addresses two things:
- Align naming around kind, which sometimes is called model.
- Convert a plain singleton into CDI produces application scoped bean.
- Change the way we are handling caches, so that we can have a cache per kind, …

Integrations

---

api/pom.xml
api/src/main/java/com/redhat/ipaas/api/v1/model/IntegrationPattern.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/CacheManagerProducer.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/DataAccessObjectProvider.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/DataManager.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/DefaultDataAccessObjectProvider.java
api/src/main/java/com/redhat/ipaas/api/v1/rest/IntegrationPatternDAO.java
api/src/test/java/com/redhat/ipaas/api/v1/rest/DataManagerTest.java
pom.xml

This pull reuqest adds a readonly DAO for integration patterns. 
Patterns are loaded from the funktion model. (stepkinds -> integration patterns).
Along with this the pull request also fixes 3 side issues:
- broken injection of cachecontainer
- broken injection of list of daos
- fetchAll not working correctly.

Introduce Integration Patterns DAO

---

circle.yml
pom.xml
runtime/pom.xml
runtime/src/main/fabric8/deployment.yml

* Prefer ipv6 stack to prevent problems on ipv6 enabled servers
* Use JBoss base image to build on
* Use correct name for image
* Use latest fabric8 maven plugin
* Push image to docker hub from circleci

Various Docker updates

---

api/src/main/java/com/redhat/ipaas/api/v1/rest/DataManager.java

@gashcrumb @jimmidyson if saving the integration keeps having issues like https://gist.github.com/gashcrumb/263c25b34e4d0bbf75139011622a3b9c
then we can disable saving to a configmap with this PR.

Saving to cache only

---

runtime/src/test/resources/ipaas-keycloak-realm.json

Add an ipaas-ui client id to the keycloak realm so that the ./start-with-keycloak.sh script in this project can be used with the default ‘yarn start’ command in the ipaas-client and have the oauth just work. (cherry picked from commit a757b75234b3c50ff28e911dd997e652261c05e9)

Add an ipaas-ui client id to the keycloak realm

---

runtime/src/main/java/com/redhat/ipaas/runtime/Application.java
runtime/src/main/java/com/redhat/ipaas/runtime/EventBusToServerSentEvents.java
runtime/src/main/java/com/redhat/ipaas/runtime/EventBusToWebSocket.java
runtime/src/main/java/com/redhat/ipaas/runtime/KeycloakConfiguration.java
runtime/src/test/java/com/redhat/ipaas/runtime/EventsITCase.java

In short none of the SB web stuff can co-exist under /api/v1 as that’s 
being handled by resteasy.  Changed the impl to use a Undertow handler
similar to the SSE impl.  The two are more closely aligned now.

Host the WebSocket endpoint under /api/v1/events.ws/*

---

jsondb/src/main/java/com/redhat/ipaas/jsondb/impl/SqlJsonDB.java

Otherwise DB records were not consistently allocated to correct object...

Ensure JsonDB orders by path

---

model/src/main/java/com/redhat/ipaas/model/integration/Integration.java

Trying to keep it as simple as possible by simply adding two fields to  `Integration`: statusType and statusPhase.
In PUT request on /integrations/<id> the statusType can be set to 'Activated' or 'Deactivated'. This would then trigger Activation or Deactivation of the integration. The runtime (kubernetes watcher?) will update the statusPhase.
Comments welcome.

WIP adding status to Integration

---

github/src/main/java/com/redhat/ipaas/github/GitHubServiceImpl.java
github/src/main/java/com/redhat/ipaas/github/SpringGitServiceFactory.java
github/src/test/java/com/redhat/ipaas/github/GitHubServiceImplTest.java

Instead of fetching all repositories and iterate over it (1 API call), fetch now the current user and fetch a repository directly (2 API calls).
It seems that this variant is not much faster, but more predictable as it not depends on the number of repoistories given.

Optimization for GitHub service

---

core/src/main/java/com/redhat/ipaas/core/Json.java
dao/src/main/resources/com/redhat/ipaas/dao/deployment.json
dao/src/test/java/com/redhat/ipaas/dao/DataManagerTest.java
dao/src/test/java/com/redhat/ipaas/dao/ReadApiClientDataTest.java
model/src/main/java/com/redhat/ipaas/model/integration/Integration.java

This is so we can activate an integration by setting the StatusType to "Activated" on the integration.
When deployment starts it then sets the StatusPhase to Pending, and when up to Running, when not up to Failed, when successfully deactivated to Succeeded. There is also an Unknown Phase just in case. We could add a StatusMessage to report errors.

Enabeling reading Enums as Strings from JSON

---

circle.yml

error: tag "latest" points to existing ImageStreamImage "ipaas-rest@sha256:2dba547c87f859dcd57e2e9ddf8fb38d4e1b03789f3d8c1aad9d11ae2f5a7cc8", it cannot be re-imported

Fixes CircleCI deployment error.

---

connector-catalog/src/main/java/com/redhat/ipaas/connector/catalog/ConnectorCatalog.java
model/src/main/java/com/redhat/ipaas/model/connection/Connector.java
openshift/pom.xml
openshift/src/main/java/com/redhat/ipaas/openshift/CreateResourcesRequest.java
openshift/src/main/java/com/redhat/ipaas/openshift/OpenShiftService.java
openshift/src/main/java/com/redhat/ipaas/openshift/OpenShiftServiceImpl.java
project-generator/pom.xml
project-generator/src/main/java/com/redhat/ipaas/project/converter/DefaultProjectGenerator.java
project-generator/src/main/java/com/redhat/ipaas/project/converter/GenerateProjectRequest.java
project-generator/src/main/java/com/redhat/ipaas/project/converter/ProjectGeneratorConfiguration.java
project-generator/src/main/java/com/redhat/ipaas/project/converter/ProjectGeneratorProperties.java
project-generator/src/main/resources/com/redhat/ipaas/project/converter/templates/application.yml.mustache
project-generator/src/main/resources/com/redhat/ipaas/project/converter/templates/pom.xml.mustache
project-generator/src/test/java/com/redhat/ipaas/project/converter/DefaultProjectGeneratorTest.java
project-generator/src/test/resources/com/redhat/ipaas/project/converter/test-application.yml
project-generator/src/test/resources/com/redhat/ipaas/project/converter/test-connectors.json
project-generator/src/test/resources/com/redhat/ipaas/project/converter/test-funktion-with-secrets.yml
project-generator/src/test/resources/com/redhat/ipaas/project/converter/test-integration.json
project-generator/src/test/resources/com/redhat/ipaas/project/converter/test-pom.xml
project-generator/src/test/resources/com/redhat/ipaas/project/converter/test-pull-push-application.yml
project-generator/src/test/resources/com/redhat/ipaas/project/converter/test-pull-push-pom.xml
rest/src/main/java/com/redhat/ipaas/rest/v1/handler/integration/IntegrationHandler.java
runtime/pom.xml
runtime/src/main/resources/application.yml

This pull requests modifies the ProjectGenerator to optionally *(its configurable)* mask secrets.
Masked secrets passed as placeholders in the URL wrapped around double squiggles, so that it can be replaced on runtime by spring-boot via `spring-cloud-kubernetes-config`.
TODO:
- also mask data inside the database (?).

IPAAS-273 Hide sensitive information

---

dao/src/main/resources/com/redhat/ipaas/dao/deployment.json

spaces around property names break e2e tests.
```html
<input class="form-control ng-untouched ng-pristine ng-valid" autocomplete="on" 
name=" accessTokenSecret" placeholder="The access token secret" spellcheck="false"
type="password" id=" accessTokenSecret">
```

[whitespace] Remove whitespace from dummy json data

---

dao/src/main/java/com/redhat/ipaas/dao/manager/DataManager.java
dao/src/test/java/com/redhat/ipaas/dao/DataManagerTest.java
rest/src/main/java/com/redhat/ipaas/rest/v1/handler/tests/TestSupportHandler.java
runtime/src/main/java/com/redhat/ipaas/runtime/SchemaCheck.java
runtime/src/main/java/com/redhat/ipaas/runtime/StoreConfiguration.java

Caching logic was not exactly right for when the cache did not hold the entire dataset (like when we restart and the dataset is in the DB but not in the cache).

Move the schema check logic to it’s own service and use it to control when the deployment.json is imported.

---

controllers/src/main/java/com/redhat/ipaas/controllers/integration/online/ActivateHandler.java
openshift/src/main/java/com/redhat/ipaas/openshift/OpenShiftServiceImpl.java

Currently mounting of the configuration secret is broken, as its mounted as lot of different files rather than a single file with multiple properties. This pull request addresses that issue.

Fix secret mount.

---

openshift/src/main/java/com/redhat/ipaas/openshift/OpenShiftConfigurationProperties.java
openshift/src/main/java/com/redhat/ipaas/openshift/OpenShiftServiceImpl.java

Ensure the generated webhook URL contains a valid hostname for the OpenShift API server.
Fixes #346

fix(github): Fix generated webhook URL

---

pom.xml
rest/src/main/java/io/syndesis/rest/Version.java

Instead of templating/resource filtering this changes the Version to
return package implementation version when packaged or fixed string
`DEVELOPMENT` when not.

refactor: alternate Versions strategy

---

runtime/pom.xml

The selected default of 30s for a single test timeout in basepom is too less as the build time has been increased considerably because of much more checks.
Fixes #387

Increase timeout for individual tests to 150s

---

pom.xml
runtime/pom.xml

The basepom default of 30s for a single integration test timeout in basepom, i.e. the tests run using failsafe plugin, is much too small for the integration tests to complete.
Previously in c91ed3454f78f9516eb98613dc21718098497e7d property `basepom.test.timeout` was set, but property `basepom.failsafe.timeout` should have been set.

Increase timeout for single integration tests to 150s

---

checkstyle-suppressions.xml
checkstyle.xml
pom.xml

This adds Checkstyle rules, these are taken from basepom-policy[1] and renamed to fit this project layout.
According to[2] Codacy should pickup the `checkstyle.xml` file.
[1] https://github.com/basepom/basepom-policy
[2] https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns

chore(build): Sync Checkstyle, Findbugs, PMD configuration with Codacy (#417)

---

verifier/src/main/java/io/syndesis/verifier/Verifier.java

This PR is related to syndesisio/syndesis-verifier#12 and syndesisio/syndesis-ui#583 where the Camel verifier didn't set the description and the immutable deserializer broke.

Fix serialization error when descriptions are missing

---

pom.xml
rest/pom.xml
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionCredentialHandler.java
rest/src/test/java/io/syndesis/rest/v1/handler/connection/ConnectionCredentialHandlerTest.java
runtime/src/test/java/io/syndesis/runtime/credential/CredentialITCase.java

When the UI specifies the return URL in credential acquisition it should be taken as an absolute path not relative path to the API base URI.
This changes to compute the absolute URI at the point the UI submits the relative URI to return to on successful OAuth acquisition.
I've also taken the opportunity to declare Mockito as _test_ dependency.

fix(credentials): Finishing OAuth credential flow on a wrong URL (#431)

---

credential/src/main/java/io/syndesis/credential/Credentials.java
credential/src/test/java/io/syndesis/credential/CredentialsTest.java
rest/src/main/java/io/syndesis/rest/v1/handler/credential/CredentialHandler.java

With this change the `state` parameter is persisted in the HTTP session.
I would like to think about this a bit, submitted for other opinions.
Crux:
- if we're now using HTTP session for OAuth1 why would we use Infinispan at all
- any trick on remaining _stateless_ with OAuth1?

fix(credentials): `state` parameter is not transfered for OAuth1 (#435)

---

credential/src/main/java/io/syndesis/credential/AcquisitionRequest.java
pom.xml
rest/pom.xml
rest/src/main/java/io/syndesis/rest/v1/JacksonContextResolver.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionCredentialHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/BaseExceptionMapper.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/ConstraintViolationExceptionMapper.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/IllegalArgumentExceptionMapper.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/ReaderExceptionMapper.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/SyndesisServerExceptionMapper.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/WriterExceptionMapper.java
rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppHandler.java
rest/src/main/java/io/syndesis/rest/v1/operations/Creator.java
rest/src/main/java/io/syndesis/rest/v1/operations/Deleter.java
rest/src/main/java/io/syndesis/rest/v1/operations/Getter.java
rest/src/main/java/io/syndesis/rest/v1/operations/Updater.java
runtime/pom.xml
runtime/src/main/resources/ValidationMessages.properties

This configures RESTEasy to validate parameters in accordance to JSR 303 (Bean Validation). It also adds JSR 303 annotations to interfaces in `io.syndesis.rest.v1.operations` package so that the standard CRUD method parameters and to other *Handler implementations so that they are all validated.
A new ExceptionMapper was added to provide JSON output in case of constraint validation.
With the specific way the exceptions are handled in RESTEasy (handler for [Reader|Writter]Exception is not looked up the inheritance chain) two ExceptionMappers to handle those are added.
And with those changes in the exception handling it made sense to create a base class for ExceptionMappers.
The only way to for the validations to work with Immutables is to use the standard Java Beans method signatures …

feat(rest): Parameter validation (#440)

---

credential/pom.xml
credential/src/main/java/io/syndesis/credential/CredentialConfiguration.java
credential/src/main/java/io/syndesis/credential/CredentialProviderConfigurer.java
credential/src/main/java/io/syndesis/credential/CredentialProviderLocator.java
credential/src/main/java/io/syndesis/credential/CredentialProviderRegistry.java
credential/src/main/java/io/syndesis/credential/salesforce/SalesforceConfiguration.java
credential/src/main/java/io/syndesis/credential/twitter/TwitterConfiguration.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java
runtime/src/test/java/io/syndesis/runtime/credential/CredentialITCase.java

The way we register CredentialProviders is not deterministic and can fail to register all CredentialProviders configured in @Configuration classes that are incorporated in the Spring Application Context after CredentialsConfiguration @Configuration class is done configuring and registering them.
This reverses the role from "I'll find you" to "I'll register with you" for CredentialProvider @Configurations. It also resurects the Configurer classes so that CredentialProviders don't end up being singletons in the Spring Application Context. They should not be accessible by other means other than through CredentialProviderLocator and it alone should handle their lifecycle.
fixes #447

fix(credentials): Determinisim in CredentialProvider registration (#447)

---

docs/design/ui-domain-object-map.adoc

This refines the descriptions of the domain trying explain in Camel terms Syndesis domain model. Also updates the links to Syndesis GitHub repositories.

chore(docs): Refine descriptions of the domain

---

dao/pom.xml
dao/src/main/java/io/syndesis/dao/manager/DataManager.java
dao/src/test/java/io/syndesis/dao/DataManagerTest.java
inspector/src/main/java/io/syndesis/inspector/DataMapperClassInspector.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/BaseExceptionMapper.java
rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppHandler.java

In the code cleanup (#426) result of the `DataManger::create` was wrongly assigned and cached as the given entity, it should be the `entityToCreate` thats being assigned if the `id` is not present.
Fixes syndesisio/syndesis-ui#662

fix(persistence): Caching and returning wrong entity from `DataManger::create`

---

pom.xml
rest/pom.xml
runtime/pom.xml
syndesis-maven-plugin/pom.xml

This reinstates the dependency plugin checks. Also of note fixes
incorrect version of jackson-annotations (resolved 2.8.0, rest of the
jackson dependencies are at 2.8.8).
A number of jersey dependencies were excluded as they are not needed.
`syndesis-maven-plugin` module was placed before the `runtime` module
in order to be built in proper order.

fix(project): Dependency issues

---

connector-catalog/src/main/java/io/syndesis/connector/catalog/ConnectorCatalogProperties.java
controllers/src/main/java/io/syndesis/controllers/integration/DemoHandlerProvider.java
controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java
credential/src/main/java/io/syndesis/credential/AcquisitionResponse.java
credential/src/main/java/io/syndesis/credential/salesforce/SalesforceConfiguration.java
credential/src/main/java/io/syndesis/credential/twitter/TwitterConfiguration.java
dao/src/main/java/io/syndesis/dao/init/ModelData.java
dao/src/main/java/io/syndesis/dao/manager/DataManager.java
github/src/main/java/io/syndesis/github/backend/FileContent.java
inspector/src/main/java/io/syndesis/inspector/ClassInspectorConfigurationProperties.java
inspector/src/main/java/io/syndesis/inspector/DataMapperClassInspector.java
model/src/main/java/io/syndesis/model/filter/Op.java
model/src/main/java/io/syndesis/model/integration/StepDeserializer.java
openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
pom.xml
rest/src/main/java/io/syndesis/rest/v1/JacksonContextResolver.java
rest/src/main/java/io/syndesis/rest/v1/handler/BaseHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorActionHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/RestError.java
rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppToCredentialsBridge.java
rest/src/main/java/io/syndesis/rest/v1/handler/tests/TestSupportHandler.java
ruleset.xml
runtime/src/main/java/io/syndesis/runtime/Application.java
runtime/src/main/java/io/syndesis/runtime/KeycloakConfiguration.java
syndesis-maven-plugin/src/main/java/io/syndesis/maven/GenerateMapperInspectionsMojo.java
verifier/src/main/java/io/syndesis/verifier/ExternalVerifierService.java

Changes to ruleset.xml:
- allows 3 asserts to be present in JUnit test (was 1)
- removes the necessity of message in asserts
- explicitly sets the types of resources that must be closed (in a hope
not to be mistaken with io.syndesis.model.connection.Connection)
- allows instantiation of objects in loops (never fully understood the
rationale behind that one)
Includes code changes to more-or-less complies with the given ruleset.

PMD ruleset tweaks, reported fixes

---

credential/src/main/java/io/syndesis/credential/CredentialProviderFactory.java
credential/src/main/java/io/syndesis/credential/Credentials.java
credential/src/main/java/io/syndesis/credential/salesforce/SalesforceConfiguration.java
credential/src/main/java/io/syndesis/credential/salesforce/SalesforceCredentialProviderFactory.java
credential/src/main/java/io/syndesis/credential/twitter/TwitterConfiguration.java
credential/src/main/java/io/syndesis/credential/twitter/TwitterCredentialProviderFactory.java
credential/src/main/resources/META-INF/spring.factories
rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppToCredentialsBridge.java

Institutes `CredentialProviderFactory` interface for creating new
`CredentialProvider` instances from, used when OAuth connector is
configured via settings page.
`CredentialProviderFactory`ies are configured through
`SpringFactoryLoader`'s `META-INF/spring.factories` and known by their
`id` property.
Now uses Credentials as a facade for registering new
`CredentialProvider`s as they are configured or bootstrapped.
Fixes an issue when trying to configure Salesforce client id/secret via
global settings.
Fixes #492

refactor(settings): Better bootstrap and configuration of OAuth settings

---

model/src/main/java/io/syndesis/model/filter/RuleFilterStep.java
model/src/test/java/io/syndesis/model/integration/StepDeserializerTest.java
model/src/test/resources/rule-filter-step.json
project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java
project-generator/src/test/java/io/syndesis/project/converter/visitor/RuleFilterStepVisitorTest.java
rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java

It's an ugly change. sorry. Instead of the typed interface
configuredProperties is used which contains values as serialized JSON strings.
Its change that way to make it happen and serious efforts should be undertaken to come to a more typed interface.
For possible options see https://github.com/syndesisio/syndesis-rest/issues/451#issuecomment-321249672

refactor(rule-filter): Adapt data format of a basic filter step according to the UI needs.

---

credential/pom.xml
credential/src/main/java/io/syndesis/credential/CredentialFlowStateHelper.java
credential/src/main/java/io/syndesis/credential/CredentialModule.java
credential/src/test/java/io/syndesis/credential/CredentialFlowStateHelperTest.java
credential/src/test/java/io/syndesis/credential/CredentialModuleTest.java
model/src/main/java/io/syndesis/model/filter/RuleFilterStep.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorCredentialHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/credential/CredentialHandler.java
rest/src/main/java/io/syndesis/rest/v1/state/ClientSideState.java
rest/src/test/java/io/syndesis/rest/v1/state/ClientSideStateTest.java

Reverts to a _conservative_ version of cookie (with the Path, HttpOnly
and Secure parameters set), the cookie should traverse back and forth
when set from UI and received on OAuth callback.
Adds Jackson module specific to
`org.springframework.social.oauth1.OAuthToken` deserialization.
Fixes #503

fix(oauth): Fixes cookie path and JSON deserialization

---

dao/src/main/resources/io/syndesis/dao/deployment.json

Adds the definition of `instanceUrl` property to the Salesforce
Connector.
Fixes #510

fix(salesforce): Declares `instanceUrl` connector property

---

credential/src/main/java/io/syndesis/credential/Credentials.java
credential/src/test/java/io/syndesis/credential/CredentialsTest.java
model/src/main/java/io/syndesis/model/connection/Connection.java
model/src/test/java/io/syndesis/model/connection/ConnectionTest.java
runtime/src/test/java/io/syndesis/runtime/credential/CredentialITCase.java

This adds a flag `derived` to Connections, derived Connections are those
that did not get their `configuredProperties` from user input but from
other means, such as OAuth dance performed by Credentials. Credentials
will also set this flag to `true` for Connections that pass successfully
through the OAuth acquisition flow and are saved at that point.
Once set the flag remains set until the UI chooses to reset it to
`false`, which it might if we ever decide to offer editing derived
Connections.
Fixes #513

feat(credentials): Mark connections as derived

---

model/src/main/java/io/syndesis/model/validation/AllValidations.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionHandler.java
rest/src/main/java/io/syndesis/rest/v1/operations/Validating.java
rest/src/main/java/io/syndesis/rest/v1/operations/Violation.java
runtime/src/test/java/io/syndesis/runtime/ConnectionsITCase.java

**Based on #495, please review it and merge before this**
Adds a new connection sub-resource (`validation`) that can be used to
perform validation of the soon-to-be created connection resource.
Full endpoint of the resource is `/api/v1/connections/validation` and
for connection payloads sent via `POST` method it will respond with
status `200` and 0-length body if the connection passes validation; or
status `409` and body containing a set of objects containing `property`
(what property) and `message` (validation message) properties.
Fixes #476

New resource for validation

---

rest/src/main/java/io/syndesis/rest/v1/ApiDocumentationEndpoint.java
runtime/src/main/java/io/syndesis/runtime/KeycloakConfiguration.java
runtime/src/test/java/io/syndesis/runtime/APIDocsITCase.java

This makes the HTML documentation available on the `/api/v1/index.html`
address (in addition to `/index.html`). The issue being is that the
route on OpenShift is defined to the `/api/v1` so `/index.html` cannot
be served from the backend.
Fixes #525

fix: The API HTML documentation are not accessible on OpenShift

---

credential/src/main/java/io/syndesis/credential/Credentials.java
credential/src/test/java/io/syndesis/credential/CredentialsTest.java
model/src/test/java/io/syndesis/model/connection/ConnectionTest.java
ruleset.xml
runtime/src/test/java/io/syndesis/runtime/ConnectionsITCase.java

This removes the inherited rule properties to make the `ruleset.xml`
cleaner, it also removes the `CloseResource` rule that was reporting
resource leak for `io.syndesis.model.connection.Connection` and sets the
maximum number of methods to `15` (from `10`).

chore: Cleanup PMD ruleset.xml

---

core/pom.xml
core/src/main/java/io/syndesis/core/Json.java
core/src/main/java/io/syndesis/core/immutable/SkipNulls.java
core/src/main/java/io/syndesis/core/json/StringTrimmingJsonDeserializer.java
core/src/main/java/io/syndesis/core/json/SyndesisModule.java
core/src/test/java/io/syndesis/core/immutable/SkipNullsTest.java
core/src/test/java/io/syndesis/core/json/StringTrimmingJsonDeserializerTest.java
dao/src/main/resources/io/syndesis/dao/demo-data.json
dao/src/test/java/io/syndesis/dao/DataManagerTest.java
model/src/main/java/io/syndesis/model/TagFinder.java
model/src/main/java/io/syndesis/model/WithName.java
project-generator/src/test/resources/io/syndesis/project/converter/test-integration.json
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppHandler.java
runtime/src/test/java/io/syndesis/runtime/ConnectionsITCase.java
runtime/src/test/java/io/syndesis/runtime/JsonHandlingITCase.java

Problem: When handling user generated input strings can be often
specified with padding whitespace, semantically humans consider those
strings with and without padding whitespace the same but computers
consider them different. Having a consistent string representation helps
with eliminating edge cases when searching or sorting.
Solution: With this all strings parsed from JSON are trimmed. Any empty
strings after trimming are set to `null`.
Introduces new Jackson module `SyndesisModule` that registers a
deserializer to perform trim-to-null on strings. As strings can appear
in collections any collection field in the model that does not tolerate
`null` strings, or does not wish to contain any `null` strings must
handle accepting `null` strings. For Immutables this is done by marking
the …

chore: String trimming JSON

---

model/pom.xml
model/src/main/java/io/syndesis/model/integration/Integration.java
model/src/test/java/io/syndesis/model/integration/IntegrationTest.java
rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java
runtime/src/test/java/io/syndesis/runtime/IntegrationsITCase.java

**Please review PRs #495 and #499 this PR is based on**
Builds upon #475 and #476 to add name uniqueness validation when
creating Integrations and provides REST API for uniqueness validation at
`POST` to `/api/v1/integrations/validation` akin to how it operates for
Connections.
Fixes #411

feature(rest): Integration name uniqueness validation

---

project-generator/pom.xml
project-generator/src/main/java/io/syndesis/project/converter/DefaultProjectGenerator.java
project-generator/src/main/java/io/syndesis/project/converter/ProjectGeneratorConfiguration.java
project-generator/src/main/java/io/syndesis/project/converter/ProjectGeneratorProperties.java
project-generator/src/main/resources/application-redhat.properties
project-generator/src/main/resources/io/syndesis/project/converter/templates/redhat/application.properties.mustache
project-generator/src/main/resources/io/syndesis/project/converter/templates/redhat/deployment.yml
project-generator/src/main/resources/io/syndesis/project/converter/templates/redhat/pom.xml.mustache
project-generator/src/main/resources/io/syndesis/project/converter/templates/redhat/settings.xml
project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java
project-generator/src/test/resources/io/syndesis/project/converter/redhat/test-application.properties
project-generator/src/test/resources/io/syndesis/project/converter/redhat/test-deployment.yml
project-generator/src/test/resources/io/syndesis/project/converter/redhat/test-pom.xml
project-generator/src/test/resources/io/syndesis/project/converter/redhat/test-pull-push-application.properties
project-generator/src/test/resources/io/syndesis/project/converter/redhat/test-pull-push-pom.xml
project-generator/src/test/resources/io/syndesis/project/converter/redhat/test-settings.xml

This PR is not to be merged but I've opened it to gather some feedback.
Now project-generator can be configured with an ``template override path`` which is the location were overriding templates are stored. In addition you can now list a number of additional resources that can be included i.e. the ``redhat`` profile includes some fabric8 bits like ``src/main/fabric8``

WIP - Generated integration project should optionally use productized FIS bom #418

---

runtime/src/main/java/io/syndesis/runtime/Application.java
runtime/src/main/java/io/syndesis/runtime/ValidatorContextResolver.java
runtime/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers

Removes the Service locator file from `META-INF/services` so that the
`ValidatorContextResolver` is not registered automatically to every
RestEasy provider instances, which is an issue with clients, and
registers `ValidatorContextResolver` only with the REST backend
`ResteasyProviderFactory` auto configured with Spring Boot.
Fixes #543

fix(validation): revises RestEasy validations

---

core/src/test/java/io/syndesis/core/json/StringTrimmingJsonDeserializerTest.java
inspector/pom.xml
inspector/src/main/java/io/syndesis/inspector/DataMapperClassInspector.java
inspector/src/test/java/io/syndesis/inspector/DataMapperClassInspectorTest.java
model/src/main/java/io/syndesis/model/filter/FilterRule.java
model/src/test/java/io/syndesis/model/integration/StepDeserializerTest.java
model/src/test/resources/filter-step.json
model/src/test/resources/rule-filter-step.json
project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java
project-generator/src/test/java/io/syndesis/project/converter/visitor/RuleFilterStepVisitorTest.java
project-generator/src/test/resources/io/syndesis/project/converter/test-filter-syndesis.yml
rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java
rest/src/test/java/io/syndesis/rest/v1/handler/IntegrationHandlerTest.java

This is not needed since only the latest output shape is used now for filtering.
Still: only java types are supported for the fields (see ClassInspector). This queries the atlasmap service internally.
Fixes #517.

refactor(filter): Remove prefix for filter options

---

model/src/main/java/io/syndesis/model/connection/ActionDefinition.java
runtime/src/test/java/io/syndesis/runtime/action/ActionDefinitionITCase.java

Swagger won't generate proper definitions if model objects don't use
bean style methods (getters/setters).

fix(model): Use bean style instead of builder

---

model/src/main/java/io/syndesis/model/connection/Action.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandler.java

With #535 action properties were moved from being directly accessible on
`Action` to a `ActionDefinition` and grouped together within
`ActionDefinitionStep`s. In order to keep backward compatibility we
could expose action properties directly on Action also.

fix(metadata): Adds backward compatibility for action properties

---

dao/pom.xml
dao/src/main/java/io/syndesis/dao/manager/DataAccessObject.java
dao/src/main/java/io/syndesis/dao/manager/DataManager.java
dao/src/main/java/io/syndesis/dao/validation/UniquePropertyValidator.java
dao/src/test/java/io/syndesis/dao/DataManagerTest.java
dao/src/test/java/io/syndesis/dao/validation/UniquePropertyValidatorTest.java
jsondb/src/main/java/io/syndesis/jsondb/JsonDB.java
jsondb/src/main/java/io/syndesis/jsondb/dao/JsonDbDao.java
jsondb/src/main/java/io/syndesis/jsondb/impl/SqlJsonDB.java
jsondb/src/test/java/io/syndesis/jsondb/impl/JsonDBTest.java
ruleset.xml
runtime/src/test/java/io/syndesis/runtime/BaseITCase.java
runtime/src/test/java/io/syndesis/runtime/ConnectionsITCase.java

The unique validation would look for a presence of a value and solely
based on that would declare it unique or non-unique. The problem with
that is, of course, that updates no longer work as it would detect it's
own value in the database and declare it non-unique. So one could create
but not update without changing the name.
This changes the lookup to return all IDs that have that unique property
with the specified value, and then if the ID of the object is contained
in those will not declare that value as non-unique.
Fixes #552

fix(validation): Don't detect updated unique properties as non unique

---

dao/src/main/resources/io/syndesis/dao/demo-data.json
model/src/main/java/io/syndesis/model/filter/FilterRule.java
model/src/test/java/io/syndesis/model/integration/StepDeserializerTest.java
model/src/test/resources/filter-step.json
project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java
project-generator/src/test/java/io/syndesis/project/converter/visitor/RuleFilterStepVisitorTest.java
project-generator/src/test/resources/io/syndesis/project/converter/test-filter-syndesis.yml

I mean simple with '.' notation to reach attributes. These would
be converted on the fly to '[..]' OGNL map access when a JSON document is moved through the route.

fic(filter): Changed back to simple for storing the expression

---

openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java

This should be probably configurable via application properties. Also it might be necessary to increase the resource limits on the BC as the default on OSO Pro is 512 MB which might be too less.

fix(runtime): Add MAVEN_OPTS to optimize build memory footprint

---

model/src/main/java/io/syndesis/model/connection/ActionPropertySuggestions.java
model/src/main/java/io/syndesis/model/connection/Connector.java
model/src/test/java/io/syndesis/model/connection/ActionPropertySuggestionsTest.java
model/src/test/resources/action-property-suggestions.json
pom.xml
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionHandler.java
rest/src/test/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandlerTest.java
runtime/pom.xml
runtime/src/test/java/io/syndesis/runtime/action/ActionSuggestionsITCase.java
runtime/src/test/resources/verifier-response-salesforce-no-properties.json
runtime/src/test/resources/verifier-response-salesforce-type-contact.json

Adds `/api/v1/connections/{connectionId}/actions/{actionId}/properties`
endpoint that responds to GET request and in the query parameters
expects any action property - value pairs that have been selected by the
user and offers suggestions as to values of other action properties.
The implementation delegates to `syndesis-verifier` and the endpoint
created in syndesision/syndesis-verifier#18[1] that in turn delegates
to Camel Metadata extension.
[1] https://github.com/syndesisio/syndesis-verifier/pull/18

chore(metadata): Adds support for dynamic action properties

---

model/src/main/java/io/syndesis/model/WithProperties.java
model/src/main/java/io/syndesis/model/connection/Connector.java
model/src/main/java/io/syndesis/model/connection/WithPropertiesBuilder.java
ruleset.xml

This allows properties being set via tags. Useful when the name of the
property is not known, but the tag is unique (enough) to use it to set
the property.

chore(tags): Set properties via tags

---

credential/pom.xml
credential/src/main/java/io/syndesis/credential/CredentialFlowState.java
credential/src/main/java/io/syndesis/credential/CredentialFlowStateHelper.java
credential/src/main/java/io/syndesis/credential/OAuth1CredentialFlowState.java
credential/src/main/java/io/syndesis/credential/OAuth2CredentialFlowState.java
credential/src/test/java/io/syndesis/credential/CredentialFlowStateHelperTest.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/credential/CredentialHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppHandler.java
rest/src/main/java/io/syndesis/rest/v1/state/ClientSideState.java
rest/src/test/java/io/syndesis/rest/v1/state/ClientSideStateTest.java
ruleset.xml
runtime/src/test/java/io/syndesis/runtime/credential/CredentialITCase.java

This changes the way credential state cookies are handled so when the
flow is unsuccessful most recent state is considered to contain
providerId (connectorId) and returnUrl. That makes the UI receive proper
callback.
Fixes #557, #464, #509

fix(credentials): Error handling in OAuth flows

---

model/src/main/java/io/syndesis/model/connection/ConfigurationProperty.java

Forgot about adding `enum` to `ConfigurationProperty`.
[1] syndesisio/syndesis-project#72

chore(metadata): Metadata model changes

---

model/src/main/java/io/syndesis/model/connection/ActionDefinition.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandler.java
rest/src/test/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandlerTest.java

If the metadata call to `syndesis-verifier` returns a property that's
not part of the connector's properties we should not throw an exception.
Also renames the method to `replaceConfigurationProperty` from
`withConfigurationProperty` as that method does not add a property to
the `ActionDescriptor` but replaces it.
Fixes #583

fix(metadata): Ignore unknown connector properties

---

pom.xml
verifier/pom.xml
verifier/src/main/java/io/syndesis/verifier/ExternalVerifierService.java

JAX-RS client used by the Verifier client was not setup with Jackson
Jdk8Module that would enable deserialization of `Optional<>` values.
Which lead to errors when deserializing verifier's response.
This creates a separate ProviderFactory and configures Jackson
ObjectMapper with the required Jdk8Module.
Fixes #578

fix(verifier): Setup the use of JDK8 with JAX-RS client

---

controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java
controllers/src/main/java/io/syndesis/controllers/integration/online/DeactivateHandler.java
controllers/src/main/java/io/syndesis/controllers/integration/online/DeleteHandler.java
model/src/main/java/io/syndesis/model/integration/Integration.java
model/src/main/java/io/syndesis/model/integration/IntegrationRevision.java
model/src/main/java/io/syndesis/model/integration/IntegrationRevisionSpec.java
model/src/main/java/io/syndesis/model/integration/IntegrationRevisionState.java
model/src/main/java/io/syndesis/model/integration/IntegrationStatus.java
openshift/src/main/java/io/syndesis/openshift/OpenShiftDeployment.java
openshift/src/main/java/io/syndesis/openshift/OpenShiftService.java
openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/tests/TestSupportHandler.java

This is a subset of https://github.com/syndesisio/syndesis-rest/pull/493, but including only changes that doesn't affect actual the API. Also, keeps behavioral changes to the bare minimum.

Maintain the integration history without breaking the api.

---

inspector/pom.xml
inspector/src/main/java/io/syndesis/inspector/DataMapperClassInspector.java
inspector/src/main/java/io/syndesis/inspector/DefaultInspectors.java
inspector/src/main/java/io/syndesis/inspector/Inspector.java
inspector/src/main/java/io/syndesis/inspector/Inspectors.java
inspector/src/main/java/io/syndesis/inspector/JsonSchemaInspector.java
inspector/src/test/java/io/syndesis/inspector/DataMapperClassInspectorTest.java
inspector/src/test/java/io/syndesis/inspector/JsonSchemaInspectorTest.java
inspector/src/test/resources/salesforce.Contact.jsonschema
model/src/main/java/io/syndesis/model/connection/DataShapeKinds.java
rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java
rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java
rest/src/test/java/io/syndesis/rest/v1/handler/IntegrationHandlerTest.java

This adds JSON schema support for filter steps. It does not invoke the
datamapper to inspect the schema as is the case with class inspections,
but instead parses the JSON schema and introspects in-process.

chore: Support JSON schema in filter steps

---

dao/pom.xml
dao/src/main/resources/io/syndesis/dao/demo-data.json
dao/src/main/resources/io/syndesis/dao/deployment.json
dao/src/test/java/io/syndesis/dao/DataManagerTest.java
dao/src/test/java/io/syndesis/dao/DeploymentDescriptorTest.java
pom.xml
project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java
project-generator/src/test/resources/io/syndesis/project/converter/test-filter-syndesis.yml
project-generator/src/test/resources/io/syndesis/project/converter/test-integration.json
project-generator/src/test/resources/io/syndesis/project/converter/test-mapper-syndesis.yml
project-generator/src/test/resources/io/syndesis/project/converter/test-pull-push-syndesis.yml
project-generator/src/test/resources/io/syndesis/project/converter/test-syndesis-with-secrets.yml
project-generator/src/test/resources/io/syndesis/project/converter/test-syndesis.yml
runtime/src/main/resources/application.yml

**Test will not pass until connectors are released**
This updates the `deployment.json` by removing the connectors that are
only for demo purposes (that is either do not work anymore or do not
have an implementation) and updating connector/action definitions to
match those in connectors.
Adds a test to make sure that the connectors defined in
`deployment.json` can be resolved and match in definition.

chore: Sync connectors with syndesis-rest

---

core/src/main/java/io/syndesis/core/immutable/ImmutablesStyle.java
credential/src/main/java/io/syndesis/credential/package-info.java
github/src/test/java/io/syndesis/github/GitHubServiceITCase.java
model/src/main/java/io/syndesis/model/connection/ActionDefinition.java
model/src/main/java/io/syndesis/model/connection/package-info.java
model/src/main/java/io/syndesis/model/environment/package-info.java
model/src/main/java/io/syndesis/model/integration/package-info.java
model/src/main/java/io/syndesis/model/package-info.java
model/src/main/java/io/syndesis/model/user/package-info.java
pom.xml
project-generator/src/main/java/io/syndesis/project/converter/package-info.java
rest/src/main/java/io/syndesis/rest/v1/operations/Violation.java
runtime/pom.xml
runtime/src/main/java/io/syndesis/runtime/JacksonContextResolver.java
runtime/src/main/java/io/syndesis/runtime/KeycloakConfiguration.java
setup/pom.xml
setup/src/main/java/io/syndesis/rest/setup/SetupApplication.java
setup/src/main/java/io/syndesis/rest/setup/SetupConfiguration.java
setup/src/main/java/io/syndesis/rest/setup/SetupHandler.java
setup/src/main/java/io/syndesis/rest/setup/keycloak/KeycloakProperties.java
setup/src/main/java/io/syndesis/rest/setup/keycloak/KeycloakSetupConfiguration.java
setup/src/main/java/io/syndesis/rest/setup/model/GitHubOAuthConfiguration.java
setup/src/main/java/io/syndesis/rest/setup/model/SetupConfigurationRequest.java
setup/src/main/java/io/syndesis/rest/setup/model/package-info.java
setup/src/main/resources/META-INF/spring.factories

The setup application provides a single endpoint, at `/api/setup`. This is
a one time only handler: once it is updated, it is unusable. The endpoint
accepts the following methods:
`GET`: This checks if setup is required. It returns `204` (`No Content`) if
the setup handler is still enabled, and `410` (`Gone`) if it is already
configured and hence can't be called again.
`PUT`: This attempts to update the configuration as requested. This handler
will return `410` (`Gone`) if configuration is no longer required. If the
endpoint is still enabled, then the handler accepts a JSON body with the
following format:
```json
{
"gitHubOAuthConfiguration": {
"clientId": "yourclientid",
"clientSecret": "topsecret"
}
}
```
The format of this is extensible for any future first time user setup
steps.
/cc …

feat(setup): Add setup JAX-RS application for first time user setup

---

dao/src/main/resources/io/syndesis/dao/deployment.json
dao/src/test/java/io/syndesis/dao/DataManagerTest.java
runtime/src/main/resources/application.yml
runtime/src/test/java/io/syndesis/runtime/action/DynamicActionSqlStoredITCase.java

SQL Stored connector id needs to be `sql-stored-connector` otherwise
when that ID is sent to verifier it will lookup the builtin `sql-stored`
Camel component.

fix: sql stored connector id

---

setup/reset-github-provider.sh

@ryordan As discussed, this adds a simple script to reset the github provider crendentials in Keycloak
and hence re-enable the initial setup API handlers.

chore(setup): Add script to easily reset Keycloak github provider client ID and secret to enable rep

---

dao/src/main/java/io/syndesis/dao/init/ReadApiClientData.java
dao/src/main/resources/io/syndesis/dao/deployment.json
dao/src/test/java/io/syndesis/dao/DataManagerTest.java
dao/src/test/java/io/syndesis/dao/ReadApiClientDataTest.java
dao/src/test/resources/io/syndesis/dao/test-data.json
runtime/src/main/resources/application.yml
runtime/src/test/java/io/syndesis/runtime/TagsITCase.java

Adding sql-stored database connection which has password set from env
Requires https://github.com/syndesisio/syndesis-openshift-templates/pull/99 to be merged so the POSTGRESQL_SAMPLEDB_PASSWORD gets set in the synthesis-rest container's env.

Adding support for setting tokens in the init data load

---

.circleci/config.yml

With the ongoing problems of JBoss EA repository, this ensures that cached dependency failures are
ignored on subsequent builds.

ci(circleci): Add -U to mvn invocation to ensure updates are pulled for missing dependencies

---

connector-catalog/pom.xml
connector-catalog/src/main/java/io/syndesis/connector/catalog/ConnectorCatalog.java
pom.xml
runtime/pom.xml
syndesis-maven-plugin/pom.xml
syndesis-maven-plugin/src/main/java/io/syndesis/maven/ExtractConnectorDescriptorsMojo.java

When creating project files, a `CamelCatalog` and `CamelConnectorCatalog`
is required to calculate the proper endpoint URL
Up to now, this is only done via Grape which does a live
introspection and download of connector jars.
A new plugin goal `syndesis:extract-connector-descriptor` has been
introduced to fetch this information offline.
By adding this to `META-INF/camel/camel-meta.json`, the runtime
can query this file and build up a CamelCatalog from this information only.
This avoids to reach out to the internet, which can have unexpected
side effects related to the performance.
-------
This is still work in progress. Actually the generation works nicely and has been introduced to the runtime pom.xml
During startup of the `ConnectorCatalog` this `/META-INF/camel/camel-meta.json` is …

feat(runtime): Prefetch connector catalog

---

openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java

Ideally this should be configurable as well as the requests/limits of the builder pod.
For our cluster we have 512 MB limit so a mx of 500M is too large.
300M should be safe, however, as said, this should be configurable.

refactor(integration): Set builder memory to 300m

---

controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java
controllers/src/main/java/io/syndesis/controllers/integration/online/BaseHandler.java
controllers/src/main/java/io/syndesis/controllers/integration/online/DeactivateHandler.java
controllers/src/main/java/io/syndesis/controllers/integration/online/DeleteHandler.java
controllers/src/main/java/io/syndesis/controllers/integration/online/OnlineHandlerProvider.java
project-generator/src/main/java/io/syndesis/project/converter/DefaultProjectGenerator.java
project-generator/src/main/java/io/syndesis/project/converter/visitor/EndpointStepVisitor.java
project-generator/src/main/java/io/syndesis/project/converter/visitor/StepVisitorContext.java
project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java
project-generator/src/test/resources/io/syndesis/project/converter/test-syndesis-with-secrets-and-multiple-connector-of-same-type.yml
project-generator/src/test/resources/io/syndesis/project/converter/test-syndesis-with-secrets.yml

The project generator now writes the syndesis.yaml like:
```yaml
---
flows:
- steps:
- kind: endpoint
uri: twitter-mention-connector:MENTIONS
- kind: endpoint
uri: http-get-connector?httpUri=www.google.com/2
- kind: endpoint
uri: twitter-search-1:cameltest?delay=1000&filterOld=true
- kind: endpoint
uri: twitter-search-2:camelprod?delay=1234&filterOld=true
- kind: endpoint
uri: http-get-connector?httpUri=www.google.com/1
```
So:
- if a connector is repeated but it does not have any component options, its scheme is preserved (see http-get-connector) 
- if a connector does have component options but it is not repeated, its scheme is preserved
- if a connector is both repeated and has component options, its scheme is suffixed with ``-${sequence}`` were the sequence is computed from the number …

Sanitize component aliaes #630 #660

---

dao/src/main/resources/io/syndesis/dao/deployment.json
dao/src/test/java/io/syndesis/dao/DeploymentDescriptorTest.java

This changes the Twitter search connector from `twitter-search` that is
the scheme of a Camel component to `twitter-search-connector`. Also adds
additional assertion to the DeploymentDescriptorTest to catch such
mismatches.
Fixes #671

fix(deployment): proper Camel scheme for Twitter search connector

---

openshift/src/main/java/io/syndesis/openshift/OpenShiftConfigurationProperties.java
openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java

It is assumed that this stream has been created outside alread, e.g. by the templating mechanism.
This PR requires an update of the templates (PR pending)

refactor: Use a reference to an existing imagestream tag for the s2i builder

---

pom.xml
project-generator/src/main/resources/io/syndesis/project/converter/templates/pom.xml.mustache
project-generator/src/test/resources/io/syndesis/project/converter/test-pom.xml
project-generator/src/test/resources/io/syndesis/project/converter/test-pull-push-pom.xml

This removes `camel-test` dependacy from the generated integration POM.
Should be few bytes less to transfer in the build.

refactor(project-generator): remove camel-test dependency

---

controllers/src/main/java/io/syndesis/controllers/integration/IntegrationController.java
controllers/src/main/java/io/syndesis/controllers/integration/StatusChangeHandlerProvider.java
controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java
controllers/src/main/java/io/syndesis/controllers/integration/online/BaseHandler.java
controllers/src/main/java/io/syndesis/controllers/integration/online/DeactivateHandler.java
controllers/src/main/java/io/syndesis/controllers/integration/online/DeleteHandler.java
model/src/main/java/io/syndesis/model/integration/Integration.java
openshift/src/main/java/io/syndesis/openshift/OpenShiftConfigurationProperties.java
openshift/src/main/java/io/syndesis/openshift/OpenShiftService.java
openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceNoOp.java
project-generator/src/main/java/io/syndesis/project/converter/DefaultProjectGenerator.java
rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java

For now we are triggering a deployment explicitly, to circumvent
issue on our target platform which has problems with deployment triggers.
However I was not able to disable image triggers on the deployment, otherwise
imagestream could not be used. This cause a double deployment on
platforms with working triggers
This is not nice but should not harm to much.

fix: Proper build and deployment handling

---

.circleci/config.yml

You can only write to the cache once, so the key needs to update if dependencies change, or else you keep missing the and re downloading the those new dependencies. Taking a hash of all poms in the project seems like a pretty good key.

specific cache key based on poms

---

rest/src/main/java/io/syndesis/rest/v1/handler/exception/InternalServerErrorExceptionMapper.java

InternalServerErrorException are thrown by JAX-RS client when the remote
service call results in an error. This adds a ExceptionMapper to convert
those exceptions to Syndesis RestError. If conversion to RestError does
not succeed a generic RestError is generated based on the HTTP status
line.

fix: adds a ExceptionMapper for InternalServerErrorExceptions

---

.mvn/maven.config
credential/pom.xml
pom.xml
project-generator/pom.xml
project-generator/src/main/resources/io/syndesis/project/converter/templates/pom.xml.mustache
project-generator/src/test/resources/io/syndesis/project/converter/test-pom.xml
project-generator/src/test/resources/io/syndesis/project/converter/test-pull-push-pom.xml
runtime/pom.xml

Upgrades Camel to 2.20.0 (from Fuse EA) and removes the Fuse EA
repository. Also adds Maven configuration intended to speed up the
build (GC configuration, 8 parallel threads for downloads).
We still need jitpack and bintray repositories, I've added them to the
POMs where those dependencies are needed to prevent Maven contacting
them for other dependencies.
Fixes #701

refactor: upgrade to Camel 2.20.0, few Maven bits

---

.circleci/config.yml

The GitHub project is gone and our cacheKey fails on circle 'can’t find the root pom at /workspace/github/pom.xml: no such file or directory'

(chore) github project is gone - updating the cacheKey

---

model/pom.xml

Getting an error building syndesis-rest because it appears like the `<ignoredUnusedDeclaredDependencies/>` needs a `<ignoredUnusedDeclaredDependency/>` tag.

Fix ignoredUnusedDeclaredDependency issue in syndesis-rest/model.

---

connector-catalog/pom.xml
connector-catalog/src/main/java/io/syndesis/connector/catalog/ConnectorCatalogProperties.java
core/pom.xml
core/src/main/java/io/syndesis/core/MavenProperties.java
project-generator/src/main/java/io/syndesis/project/converter/DefaultProjectGenerator.java
project-generator/src/main/java/io/syndesis/project/converter/ProjectGeneratorProperties.java
project-generator/src/main/resources/io/syndesis/project/converter/templates/pom.xml.mustache
project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java
project-generator/src/test/resources/io/syndesis/project/converter/test-pull-push-pom.xml
runtime/src/main/java/io/syndesis/runtime/Application.java
runtime/src/main/resources/application.yml
syndesis-builder-image-generator/src/main/java/io/syndesis/image/Application.java

Adds MavenProperties that currently holds only Maven repositories that
the connector catalog, project generator and builder image generator
use.
Defines by default to use only Maven central.
Fixes #664

refactor: use same Maven repositories thought

---

credential/src/test/java/io/syndesis/credential/CredentialsTest.java
rest/pom.xml
rest/src/main/java/io/syndesis/rest/v1/handler/exception/BaseExceptionMapper.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/ErrorMap.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/HttpClientErrorExceptionMapper.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/HttpServerErrorExceptionMapper.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/InternalServerErrorExceptionMapper.java
rest/src/main/java/io/syndesis/rest/v1/handler/exception/RestError.java
rest/src/test/java/io/syndesis/rest/v1/handler/exception/ErrorMapTest.java
rest/src/test/resources/HttpClientErrorException.json
rest/src/test/resources/HttpClientErrorException.xml

Best effort parsing of the raw error message, with a fallback of sending the raw message. This message is set in the userMsgDetail.
https://github.com/syndesisio/syndesis-rest/issues/679
https://github.com/syndesisio/syndesis-rest/issues/652
Let's simply add more parsers as they different raw formats are found.

Improving handling of Oauth exceptions

---

dao/pom.xml
dao/src/test/java/io/syndesis/dao/DeploymentDescriptorIT.java

Renames DeploymentDescriptor to DeploymentDescriptorIT and adds failsafe
plugin to POM to be executed.
Fixes #715

refactor: make DeploymentDescriptor integration test

---

controllers/src/main/java/io/syndesis/controllers/ControllersConfigurationProperties.java
controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java

This allows setting the limit of integrations or deployments to `0` to
signify unlimited number of integrations or deployments. Useful when
developing or testing.

refactor: option for unlimited integrations/deployments per user

---

README.md
rest/src/main/java/io/syndesis/rest/v1/V1Application.java

#382 red icon on README.md and https://github.com/syndesisio/syndesis-rest/issues/646
Issue 1 is that circle-ci changed the api to their build artifacts: https://circleci.com/docs/2.0/artifacts/#downloading-all-artifacts-for-a-build-on-circleci
So we can no longer have a direct link to the swagger.json on circle-ci. Only a link to a document with links: https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-rest/latest/artifacts. Next best thing seems to use the link to staging.
Issue 2 our swagger.json is not valid as it is missing a title attribute, causing the red error icon.
> {"messages":["attribute info.title is missing"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"required","message":"object has missing required properties …

Fixing invalid swagger link issues #382

---

rest/src/main/java/io/syndesis/rest/v1/handler/user/UserHandler.java
rest/src/test/java/io/syndesis/rest/v1/handler/user/UserHandlerTest.java

Needed for TP2 if we want user info safely populated in UI.

fix: Handle missing user info in OpenShift user object

---

runtime/src/main/java/io/syndesis/runtime/SecurityConfiguration.java

By providing default AuthenticationManager bean to Spring application
context Spring Security auto configuration
(o.s.b.a.s.AuthenticationManagerConfiguration) is not triggered, and no
in-memory user details service will be created. This prevents the
message:
Using default security password: ...
from being displayed at startup.

refactor: provide default AuthenticationManager

---

openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java

This ensures that old RCs are cleaned up and that we do not hit limits related to this.
Fixes #739

fix: Explicitly set the deployment history limit to 0

---

filestore/pom.xml
filestore/src/main/java/io/syndesis/filestore/FileStore.java
filestore/src/main/java/io/syndesis/filestore/FileStoreException.java
filestore/src/main/java/io/syndesis/filestore/impl/FileStoreSupport.java
filestore/src/main/java/io/syndesis/filestore/impl/SqlFileStore.java
filestore/src/test/java/io/syndesis/filestore/impl/SqlFileStoreTest.java
pom.xml
runtime/pom.xml
runtime/src/main/java/io/syndesis/runtime/DataSourceConfiguration.java
runtime/src/main/java/io/syndesis/runtime/DataStoreConfiguration.java
runtime/src/main/java/io/syndesis/runtime/FileStoreConfiguration.java
runtime/src/main/resources/application.yml
runtime/src/test/java/io/syndesis/runtime/BaseITCase.java

First PR on syndesis :smile: 
This fixes #735.
It adds a Filestore that can be used to store binary artifacts such as JARs.
The interface allows to do operation on filesystem-like paths and can be adapted to store artifacts in whatever storage we want in the future.
Current implementation uses a DB table called `filestore` inside the postgres database with 2 columns (`path` and `data`).
All the required file operation should be already implemented (write, load, move, delete and temp file support). Others can be added as needed.

Adding filestore with DB backend

---

pom.xml
project-generator/src/main/resources/io/syndesis/project/converter/templates/pom.xml.mustache

This must not be replaced by the pipeline builds as the Fuse Repo is not added in the runtime pom.xml

refactor: Use separate version number for the Maven runtime

---

core/src/main/java/io/syndesis/core/MavenProperties.java
project-generator/src/test/resources/io/syndesis/project/converter/test-pull-push-pom.xml
runtime/src/main/resources/application.yml

This sorts configured Maven repositories by their keys as a simple
priority mechanism. Now if we specify environment variable like:
MAVEN_REPOSITORIES_00_some_where=http://over.the.rainbow
The order of generated `pom.xml` of the integration pod and order by
which Grape resolves artifacts of Camel Connectors should be affected.

refactor: sort Maven repositories

---

filestore/src/main/java/io/syndesis/filestore/impl/SqlFileStore.java
filestore/src/test/java/io/syndesis/filestore/impl/SqlFileStoreTest.java

This fixes a issue that caused an attempt to reinitialize the DB. The database type is auto-detected and the "filestore" table is not created if it already exists.

Fix filestore initialization on different DB

---

model/src/main/java/io/syndesis/model/integration/Integration.java
model/src/main/java/io/syndesis/model/integration/IntegrationRevision.java
model/src/main/java/io/syndesis/model/integration/IntegrationRevisionSpec.java
model/src/main/java/io/syndesis/model/integration/IntegrationRuntime.java
model/src/main/java/io/syndesis/model/integration/IntegrationStatus.java
model/src/main/java/io/syndesis/model/integration/SimpleStep.java
model/src/main/java/io/syndesis/model/integration/StepDeserializer.java

The only functional difference is addition of `@SkipNulls` annotation
that filters out SimpleStep.configuredProperties that contain `null`
values. Issue that manifests itself when trying to add a mapping step to
an integration and having no mapping defined at that point, in JSON it
looks like:
{
"configuredProperties": {
"atlasmapping": ""
}
}
That is converted by `StringTrimmingJsonDeserializer` to
`(atlasmapping, null)`, and in trun results in a NullPointerException
when trying to deserialize the JSON.
Also adds a few `@Override` annotations, comments to empty blocks.

refactor: cleanup integration model

---

dao/src/main/java/io/syndesis/dao/ExtensionDao.java
jsondb/src/main/java/io/syndesis/jsondb/dao/ExtensionJsonDbDao.java
model/src/main/java/io/syndesis/model/Kind.java
model/src/main/java/io/syndesis/model/extension/Extension.java
pom.xml
rest/pom.xml
rest/src/main/java/io/syndesis/rest/v1beta1/V1Beta1Application.java
rest/src/main/java/io/syndesis/rest/v1beta1/V1Beta1Configuration.java
rest/src/main/java/io/syndesis/rest/v1beta1/handler/extension/ExtensionHandler.java
rest/src/main/java/io/syndesis/rest/v1beta1/util/ExtensionAnalyzer.java
rest/src/main/resources/META-INF/spring.factories
runtime/src/main/resources/application.yml
runtime/src/test/java/io/syndesis/runtime/BaseITCase.java
runtime/src/test/java/io/syndesis/runtime/ExtensionsITCase.java
runtime/src/test/java/io/syndesis/runtime/T3stSupportITCase.java
runtime/src/test/resources/application-test.yml

This adds a API to manage tech extensions. These are a subset of the [API described in the extension doc](https://github.com/lburgazzoli/syndesis-project/blob/github-125-tech-extension/proposals/125-tech-extension.adoc#api). Other issues are tracking remaining operations.
Supported operations are:
- POST (this accepts a binary artifact and returns the JSON metadata of the extension)
- LIST
- GET
- DELETE
API are published under "/api/v1beta1". Beta api are disabled by default. They can be enabled with toggles (env var on Deployment):
```
FEATURES_API_V1BETA1_ENABLED=true
FEATURES_FILESTORE_ENABLED=true
```
I've put a toggle also for the "v1" api, but it's enabled by default.
When a binary artifact is uploaded, it's stored in "/extensions/[id]" into the filestore (same id of the entity in …

Fixes #736: Add API to manage tech extensions

---

runtime/src/main/java/io/syndesis/runtime/SecurityConfiguration.java

This allows specifying Spring profile to be `development`, for instance
via Java property `spring.profiles.active` (i.e.
`-Dspring.profiles.active=development`) to disable pre-authenticated
security and the ACLs defined within `SpringConfiguration`. This allows
local development and invoking REST API via HTTP client (e.g. `curl`)
without specifying any Cookies or other authentication headers.

feat: disable security in `development` profile

---

dao/src/main/java/io/syndesis/dao/validation/extension/NoDuplicateExtensionValidator.java
dao/src/main/resources/META-INF/validation/extension-constraint.xml
model/src/main/java/io/syndesis/model/extension/Extension.java
model/src/main/java/io/syndesis/model/validation/NonBlockingValidations.java
model/src/main/java/io/syndesis/model/validation/extension/NoDuplicateExtension.java
rest/src/main/java/io/syndesis/rest/v1beta1/handler/extension/ExtensionHandler.java
rest/src/main/java/io/syndesis/rest/v1beta1/util/ExtensionAnalyzer.java
runtime/src/main/resources/messages.properties
runtime/src/test/java/io/syndesis/runtime/ExtensionsITCase.java

This adds services to validate the tech extension in order to detect blocking/non-blocking errors (the HTTP status code determines the kind of errors). Both kind of alerts are computed using bean validation. I've used the `NonBlockingValidation` group for checking non-blocking errors.

Fixes #141: Add validation to tech extension API

---

Jenkinsfile

So, as of openshift 3.6.0 our approach of mounting m2 settings under ~/.m2 and local maven repo under ~/.m2/repository ( a mount within a mount ) does no longer work.
We need to use different paths.

refactor: use the image provided m2 repository.

---

runtime/pom.xml

HTTP Components we use via Resteasy JAX-RS client require `commons-io`,
this adds `commons-io` as compile dependency.
Fixes #806

fix: redeclare commons-io as compile dependency

---

rest/src/main/java/io/syndesis/rest/v1/handler/exception/ClientErrorExceptionMapper.java

Adds exception mapper to better handle client errors. Previously client
errors were equated with 500 internal server error, for JAX-RS client
errors have appropriate status codes and messages this surfaces those.

feat: client error exception mapper
