runtime/src/main/java/com/redhat/ipaas/rest/ComponentGroups.java, runtime/src/main/java/com/redhat/ipaas/rest/Components.java, runtime/src/main/java/com/redhat/ipaas/rest/Connections.java, runtime/src/main/java/com/redhat/ipaas/rest/DataManager.java, runtime/src/main/java/com/redhat/ipaas/rest/IntegrationPatterns.java, runtime/src/main/java/com/redhat/ipaas/rest/Permissions.java, runtime/src/main/java/com/redhat/ipaas/rest/Roles.java, runtime/src/main/java/com/redhat/ipaas/rest/Users.java
The benefit is that we now have a single isntance of the DataManger which is initialized just once.
@KurtStam: Not sure If this breaks something, so wdyt?
=> #3 DataManager is now managed by CDI.

api/pom.xml, pom.xml, runtime/pom.xml, runtime/src/main/java-templates/com/redhat/ipaas/runtime/Version.java, runtime/src/main/java/com/redhat/ipaas/runtime/Main.java, swagger-ui/pom.xml, swagger-ui/src/main/java-templates/com/redhat/ipaas/swaggerui/Version.java, swagger-ui/src/main/resources/index.html
=> Working swagger ui custom index.html and pom updates

circle.yml, runtime/pom.xml
=> Put fabric8 mvn tooling in fabric8 profile

readme.md, runtime/ipaas-realm.json, runtime/pom.xml, runtime/src/main/java/com/redhat/ipaas/runtime/Main.java, runtime/src/main/resources/keycloak.json
=> Issue11 hookup keycloak

pom.xml
=> Use released maven dependency plugin

api/src/main/java/com/redhat/ipaas/api/v1/model/ListResult.java, api/src/main/java/com/redhat/ipaas/api/v1/rest/DataManager.java, api/src/main/java/com/redhat/ipaas/api/v1/rest/util/PaginationFilter.java, api/src/main/java/com/redhat/ipaas/api/v1/rest/util/ReflectiveSorter.java, api/src/test/java/com/redhat/ipaas/api/v1/rest/DataManagerTest.java, api/src/test/java/com/redhat/ipaas/api/v1/rest/util/PaginationFilterTest.java, api/src/test/java/com/redhat/ipaas/api/v1/rest/util/ReflectiveSorterTest.java
=> Pass ListResult to list filters to be able to change total count if necessary

api/src/main/java/com/redhat/ipaas/api/v1/rest/JacksonContextResolver.java
Absent deals with empty Optionals as well as nulls
=> Serialize non-absent to work better with Java8 Optionals

runtime/pom.xml
=> Remove okhttp dependency - inherit from kube client

.gitignore, model2/pom.xml, model2/src/main/java/com/redhat/ipaas/model2/Action.java, model2/src/main/java/com/redhat/ipaas/model2/ActionInstance.java, model2/src/main/java/com/redhat/ipaas/model2/ActionInstanceProperty.java, model2/src/main/java/com/redhat/ipaas/model2/ActionProperty.java, model2/src/main/java/com/redhat/ipaas/model2/ConfiguredConnector.java, model2/src/main/java/com/redhat/ipaas/model2/ConfiguredConnectorProperty.java, model2/src/main/java/com/redhat/ipaas/model2/Connector.java, model2/src/main/java/com/redhat/ipaas/model2/ConnectorProperty.java, model2/src/test/java/com/redhat/ipaas/model2/ActionTest.java, model2/src/test/java/com/redhat/ipaas/model2/ConfiguredConnectionTest.java, model2/src/test/java/com/redhat/ipaas/model2/ConnectorTest.java, model2/src/test/resources/META-INF/persistence.xml, pom.xml
Don't merge, just looking for some early feedback on the entity mapping.
=> WIP first entity layout

dao/src/main/java/com/redhat/ipaas/dao/init/ReadApiClientData.java, dao/src/main/resources/com/redhat/ipaas/dao/deployment.json, dao/src/test/java/com/redhat/ipaas/dao/DataManagerTest.java, model/src/main/java/com/redhat/ipaas/model/connection/Connector.java, model/src/main/java/com/redhat/ipaas/model/integration/Step.java
First outline of the Timed Integration using Steps. Note that the property values still need to be set.
Values settings for an Action would be the Step.configuredProperties field. 
@gashcrumb please take a look.
- I had to add `Connection` to `Step` so that we have access to connection properties, in addition to the `Action`.
- I added a List of Actions to Connection, and I organized the actions as part of the connection in the deployment.json
- I also updated the Twitter to Salesforce example to use steps.
=> Setting the Integration Data in the Steps

connector-catalog/pom.xml, connector-catalog/src/main/java/com/redhat/ipaas/connector/catalog/ConnectorCatalog.java, connector-catalog/src/main/java/com/redhat/ipaas/connector/catalog/ConnectorCatalogConfiguration.java, connector-catalog/src/main/java/com/redhat/ipaas/connector/catalog/ConnectorCatalogProperties.java, connector-catalog/src/main/resources/META-INF/spring.factories, connector-catalog/src/main/resources/spring.factories, integration-to-maven-project-converter/pom.xml, integration-to-maven-project-converter/src/main/java/com/redhat/ipaas/project/converter/ConverterConfiguration.java, integration-to-maven-project-converter/src/main/java/com/redhat/ipaas/project/converter/DefaultIntegrationToProjectConverter.java, integration-to-maven-project-converter/src/main/java/com/redhat/ipaas/project/converter/IntegrationToProjectConverter.java, integration-to-maven-project-converter/src/main/resources/META-INF/spring.factories, integration-to-maven-project-converter/src/main/resources/com/redhat/ipaas/project/converter/templates/Application.java.mustache, integration-to-maven-project-converter/src/main/resources/com/redhat/ipaas/project/converter/templates/README.md.mustache, integration-to-maven-project-converter/src/main/resources/com/redhat/ipaas/project/converter/templates/application.yml.mustache, integration-to-maven-project-converter/src/main/resources/com/redhat/ipaas/project/converter/templates/pom.xml.mustache, integration-to-maven-project-converter/src/test/java/com/redhat/ipaas/project/converter/DefaultIntegrationToProjectConverterTest.java, integration-to-maven-project-converter/src/test/resources/com/redhat/ipaas/project/converter/test-Application.java, integration-to-maven-project-converter/src/test/resources/com/redhat/ipaas/project/converter/test-README.md, integration-to-maven-project-converter/src/test/resources/com/redhat/ipaas/project/converter/test-application.yml, integration-to-maven-project-converter/src/test/resources/com/redhat/ipaas/project/converter/test-funktion.yml, integration-to-maven-project-converter/src/test/resources/com/redhat/ipaas/project/converter/test-integration.json, integration-to-maven-project-converter/src/test/resources/com/redhat/ipaas/project/converter/test-pom.xml, integration-to-maven-project-converter/src/test/resources/com/redhat/ipaas/project/converter/test-pull-push-README.md, integration-to-maven-project-converter/src/test/resources/com/redhat/ipaas/project/converter/test-pull-push-application.yml, integration-to-maven-project-converter/src/test/resources/com/redhat/ipaas/project/converter/test-pull-push-funktion.yml, integration-to-maven-project-converter/src/test/resources/com/redhat/ipaas/project/converter/test-pull-push-pom.xml, model/src/main/java/com/redhat/ipaas/model/integration/Step.java, pom.xml, rest/pom.xml, runtime/src/main/java/com/redhat/ipaas/runtime/Application.java
@gashcrumb @KurtStam This turns integrations from UI in form of:
```json
{
"id": "test-integration",
"name": "Test Integration",
"description": "This is a test integration!",
"gitRepo": "https://ourgithhost.somewhere/test.git",
"steps": [
{
"stepKind": "endpoint",
"connection": {
"configuredProperties": "{\"timerName\": \"every\"}"
},
"configuredProperties": "{\"period\": \"5000\"}",
"action": {
"camelConnectorPrefix": "periodic-timer"
}
},
{
"stepKind": "endpoint",
"connection": {
"configuredProperties": "{}"
},
"configuredProperties": "{\"httpUri\": \"http://localhost:8080/hello\"}",
"action": {
"camelConnectorPrefix": "http-get"
}
},
{
"stepKind": "log",
"configuredProperties": "{\"message\": \"Hello World! ${body}\"}",
},
{
"stepKind": "endpoint",
"connection": { …
```
=> WIP: Initial work on integration to project converter

dao/src/main/resources/com/redhat/ipaas/dao/deployment.json, model/src/main/java/com/redhat/ipaas/model/connection/DataShape.java
https://github.com/redhat-ipaas/ipaas-rest/issues/226
=> Adding In/OutputDataType values to the example data

runtime/pom.xml
=> Revert java base image to 1.2.3 (1.8.0_111)

model/src/main/java/com/redhat/ipaas/model/integration/Integration.java, rest/src/main/java/com/redhat/ipaas/rest/v1/handler/integration/IntegrationHandler.java
adding lastUpdated (date) and timesUsed (big int) on Integration.
=> issue #246

dao/src/main/resources/com/redhat/ipaas/dao/deployment.json, model/src/main/java/com/redhat/ipaas/model/integration/Integration.java, runtime/src/main/resources/application.yml
Added the Integration.statusMessage back, and added a message for the Timed integration example. 
I also increased the db version so it will refresh the data on staging when merged and deployed.
=> adding statusMessage

dao/src/main/resources/com/redhat/ipaas/dao/deployment.json, model/src/main/java/com/redhat/ipaas/model/connection/DataShape.java
Splitting DataShape.dataType up into kind and type
=> issue #274

dao/src/main/resources/com/redhat/ipaas/dao/deployment.json, model/src/main/java/com/redhat/ipaas/model/connection/Connection.java, project-generator/src/test/resources/com/redhat/ipaas/project/converter/test-integration.json, runtime/src/main/resources/application.yml
As discussed on IRC.
Fixes #278, fixes #281
=> Remove position property from Connector

runtime/src/test/java/com/redhat/ipaas/runtime/Recordings.java
=> Synchronize Recordings.invoke to fix flaky test

dao/src/main/resources/com/redhat/ipaas/dao/deployment.json, pom.xml, runtime/src/main/resources/application.yml
Fixes https://issues.jboss.org/browse/IPAAS-293
=> Trade Insight API: Add Sell and Top recommendation actions

pom.xml
Should give us more info for #297 and #272.
=> chore(kubernetes-client): version bump to 2.2.13 to include better error messages in logs

controllers/pom.xml, controllers/src/main/java/com/redhat/ipaas/controllers/ActivateHandler.java, controllers/src/main/java/com/redhat/ipaas/controllers/ControllersConfiguration.java, controllers/src/main/java/com/redhat/ipaas/controllers/DeactivateHandler.java, controllers/src/main/java/com/redhat/ipaas/controllers/DeleteHandler.java, controllers/src/main/java/com/redhat/ipaas/controllers/IntegrationController.java, controllers/src/main/java/com/redhat/ipaas/controllers/WorkflowHandler.java, controllers/src/main/resources/META-INF/spring.factories, core/pom.xml, core/src/main/java/com/redhat/ipaas/core/Names.java, core/src/main/java/com/redhat/ipaas/core/Tokens.java, core/src/test/java/com/redhat/ipaas/core/NamesTest.java, github/pom.xml, github/src/main/java/com/redhat/ipaas/github/GitHubConfiguration.java, github/src/main/java/com/redhat/ipaas/github/GitHubService.java, github/src/main/java/com/redhat/ipaas/github/GitHubServiceImpl.java, github/src/main/java/com/redhat/ipaas/github/GitHubServiceNoOp.java, github/src/main/java/com/redhat/ipaas/github/backend/KeycloakTokenAwareGitHubClient.java, github/src/test/java/com/redhat/ipaas/github/GitHubServiceImplTest.java, model/src/main/java/com/redhat/ipaas/model/integration/Integration.java, openshift/pom.xml, openshift/src/main/java/com/redhat/ipaas/openshift/OpenShiftDeployment.java, openshift/src/main/java/com/redhat/ipaas/openshift/OpenShiftService.java, openshift/src/main/java/com/redhat/ipaas/openshift/OpenShiftServiceImpl.java, openshift/src/main/java/com/redhat/ipaas/openshift/OpenShiftServiceNoOp.java, openshift/src/main/java/com/redhat/ipaas/openshift/ScaleRequest.java, pom.xml, rest/pom.xml, rest/src/main/java/com/redhat/ipaas/rest/v1/handler/integration/IntegrationHandler.java
It still needs testing, thus the WIP label.
=> [WIP] Activate deactivate

controllers/src/main/java/com/redhat/ipaas/controllers/ActivateHandler.java, github/src/main/java/com/redhat/ipaas/github/GitHubService.java, github/src/main/java/com/redhat/ipaas/github/GitHubServiceImpl.java, github/src/main/java/com/redhat/ipaas/github/GitHubServiceNoOp.java, project-generator/src/main/java/com/redhat/ipaas/project/converter/DefaultProjectGenerator.java, project-generator/src/main/java/com/redhat/ipaas/project/converter/GenerateProjectRequest.java, project-generator/src/main/resources/com/redhat/ipaas/project/converter/templates/README.md.mustache, project-generator/src/main/resources/com/redhat/ipaas/project/converter/templates/application.yml.mustache, project-generator/src/test/java/com/redhat/ipaas/project/converter/DefaultProjectGeneratorTest.java, project-generator/src/test/resources/com/redhat/ipaas/project/converter/test-README.md, project-generator/src/test/resources/com/redhat/ipaas/project/converter/test-pull-push-README.md
This adds the current API's user to the GitHub URL within the README in the form `https://github.com/<user>/<repoName>.git`
~~Still work in progress, needs to be verified E2E~~ Verified
Fixes #288, fixes #162
=> Add user part to template's URL #288

dao/src/main/resources/com/redhat/ipaas/dao/deployment.json, dao/src/test/java/com/redhat/ipaas/dao/ReadApiClientDataTest.java, model/src/main/java/com/redhat/ipaas/model/connection/Connection.java, model/src/main/java/com/redhat/ipaas/model/integration/Integration.java, rest/src/main/java/com/redhat/ipaas/rest/v1/handler/connection/ConnectionHandler.java, rest/src/main/java/com/redhat/ipaas/rest/v1/handler/integration/IntegrationHandler.java, runtime/src/main/resources/application.yml
@kahboom does this look good to you?
=> adding createdDate

rest/src/main/java/com/redhat/ipaas/rest/v1/handler/exception/EntityNotFoundExceptionMapper.java, rest/src/main/java/com/redhat/ipaas/rest/v1/handler/exception/IPaasServerExceptionMapper.java, rest/src/main/java/com/redhat/ipaas/rest/v1/handler/exception/IllegalArgumentExceptionMapper.java, rest/src/main/java/com/redhat/ipaas/rest/v1/handler/exception/RestError.java, rest/src/main/java/com/redhat/ipaas/rest/v1/operations/Getter.java, runtime/src/test/java/com/redhat/ipaas/runtime/BaseITCase.java, runtime/src/test/java/com/redhat/ipaas/runtime/IntegrationsITCase.java, runtime/src/test/java/com/redhat/ipaas/runtime/T3stSupportITCase.java
Update tests to check that exception mappers are being used. Also a few other tidy up tests stuff.
=> Use JAX-RS exception mappers instead of Spring default mappers

controllers/src/main/java/com/redhat/ipaas/controllers/ActivateHandler.java, model/src/main/java/com/redhat/ipaas/model/integration/Step.java, project-generator/src/main/java/com/redhat/ipaas/project/converter/DefaultProjectGenerator.java, project-generator/src/test/java/com/redhat/ipaas/project/converter/DefaultProjectGeneratorTest.java
=> Making ConfiguredProperties Optional, issue #300

dao/src/main/resources/com/redhat/ipaas/dao/deployment.json, dao/src/test/java/com/redhat/ipaas/dao/DataManagerTest.java, runtime/src/main/resources/application.yml
https://issues.jboss.org/browse/IPAAS-294
=> Adding some connectors that don't actually exist yet

controllers/src/main/java/com/redhat/ipaas/controllers/DemoActivateHandler.java, controllers/src/main/java/com/redhat/ipaas/controllers/DemoDeactivateHandler.java, controllers/src/main/java/com/redhat/ipaas/controllers/DemoDeleteHandler.java, controllers/src/main/java/com/redhat/ipaas/controllers/IntegrationController.java, controllers/src/main/java/com/redhat/ipaas/controllers/NoopHandler.java, controllers/src/main/java/com/redhat/ipaas/controllers/OnlineActivateHandler.java, controllers/src/main/java/com/redhat/ipaas/controllers/OnlineDeactivateHandler.java, controllers/src/main/java/com/redhat/ipaas/controllers/OnlineDeleteHandler.java, runtime/src/main/resources/application.yml, runtime/src/test/resources/application-test.yml
The demo version move to the desired state after 2 seconds.
=> IPAAS-314: Have an Online and Demo versions of the workflow handlers.

dao/src/main/resources/com/redhat/ipaas/dao/deployment.json, runtime/src/main/resources/application.yml
A few more integrations that are fixed in various states just so the view can be further developed
=> Need more sample integrations in various states #318

rest/src/main/java/com/redhat/ipaas/rest/v1/handler/integration/IntegrationHandler.java
Corrected to the proper status.
Fixes #342
=> Fix integration deactivation

rest/src/main/java/com/redhat/ipaas/rest/v1/handler/tests/TestSupportHandler.java
Executing `/test-support/` resources is kind of sensitive operation.
Add logging of endpoint iexecutions.
Example log output 
```
2017-04-27 13:41:32.396  WARN [-,6d9acee66da1a3e8,6d9acee66da1a3e8,false] 1 --- [  XNIO-3 task-3] c.r.i.r.v.h.tests.TestSupportHandler     : user 998edc9d-9fa3-4c68-aa89-cc4a254ff663 is resetting DB
```
=> [log] Log test-support endpoint usage

docs/design/ui-domain-object-map.adoc
so that it can be found easier
=> Copied some concept docs from the wiki to the repo

core/src/main/java/io/syndesis/core/KeyGenerator.java, core/src/test/java/io/syndesis/core/KeyGeneratorTest.java
=> test: Add unit tests for the KeyGenerator

project-generator/pom.xml, project-generator/src/main/resources/io/syndesis/project/converter/templates/pom.xml.mustache, project-generator/src/test/resources/io/syndesis/project/converter/test-pom.xml, project-generator/src/test/resources/io/syndesis/project/converter/test-pull-push-pom.xml
=> fix(project-generator): Use project properties in dependency declarations rather than direct version

dao/src/main/resources/io/syndesis/dao/deployment.json, pom.xml, project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java, project-generator/src/test/resources/io/syndesis/project/converter/test-integration.json, project-generator/src/test/resources/io/syndesis/project/converter/test.properties, runtime/src/main/resources/application.yml
Note that the twitter-search-connector is new and still needs to be released from the syndesisio/connectors project
=> Create Camel Component for Twitter (keyword) Search #384

core/src/main/java/io/syndesis/core/KeyGenerator.java, core/src/test/java/io/syndesis/core/KeyGeneratorTest.java
Current KeyGenerator implementation is not thread safe, demonstrated by the flakiness of `io.syndesis.jsondb.impl.JsonDBTest::testPush` test.
=> fix(core): The KeyGenerator is not thread safe (#422)

core/src/main/java/io/syndesis/core/SuppressFBWarnings.java, dao/src/main/resources/io/syndesis/dao/deployment.json, model/src/main/java/io/syndesis/model/connection/ConfigurationProperty.java, model/src/main/java/io/syndesis/model/connection/Connector.java, rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppHandler.java, runtime/src/main/resources/application.yml, runtime/src/test/java/io/syndesis/runtime/SetupITCase.java
Also:
- Adds tags field to properties
- Adds configuredProperties to Connectors
- Increments the schema version
=> Issue #424 Add REST api to oauth client id/secret resources for the setup page

controllers/pom.xml, pom.xml, rest/src/main/java/io/syndesis/rest/v1/V1Application.java, runtime/pom.xml, runtime/src/main/resources/application.yml
=> chore: Refactor resteasy dependencies to move to spring bean registry scanning for JAX-RS applicatio

credential/pom.xml, credential/src/main/java/io/syndesis/credential/salesforce/SalesforceConfiguration.java, credential/src/main/java/io/syndesis/credential/twitter/TwitterConfiguration.java, credential/src/test/java/io/syndesis/credential/salesforce/SalesforceApplicatorTest.java, pom.xml, rest/pom.xml, rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppHandler.java, rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppToCredentialsBridge.java, runtime/pom.xml, runtime/src/test/java/io/syndesis/runtime/SetupITCase.java
When a user updates the oauth id/secret for a connection in the settings page, the oauth credentials registry now gets updated.
=> Integrated the global settings for oauth apps issues #424 and syndesisio/syndesis-ui#556.

rest/src/main/java/io/syndesis/rest/v1/handler/tests/TestSupportHandler.java
Enables TestSupport to delete OpenShift deployments.
=> [TestSupport] Enable to delete deployments

model/src/main/java/io/syndesis/model/filter/RuleFilterStep.java
that's the result of hectic PRs with no patience for waiting on reviews ;-(
=> fix(rule-filter): Silly condition bug

Jenkinsfile
This keeps up to 5 builds and 5 artifacts (if archived) from the build.
=> chore(build): Discard old builds

controllers/pom.xml, controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java, github/src/main/java/io/syndesis/git/GitWorkflow.java, github/src/main/java/io/syndesis/github/GitHubService.java, github/src/main/java/io/syndesis/github/GitHubServiceImpl.java, github/src/main/java/io/syndesis/github/GitHubServiceNoOp.java, github/src/test/java/io/syndesis/github/GitHubServiceITCase.java, project-generator/pom.xml, project-generator/src/main/java/io/syndesis/project/converter/package-info.java, project-generator/src/main/resources/io/syndesis/project/converter/templates/README.md.mustache, project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java
=> fix(github): Set commit author name and email from github retrieved info

rest/src/main/java/io/syndesis/rest/v1/handler/setup/OAuthAppHandler.java
Builds on #572 so have a look at that first
In the effort to remove OAuth configuration OAuth settings endpoint must
allow empty or null values. With trim-to-null empty values were
transformed to null and this did not allow the Connector's configured
properties to be updated. This builds on the PR#572 and allows setting
empty values for OAuth properties in the effort to remove those from
`configuredProperties`.
Fixes #536
=> fix(settings): Allows updating OAuth settings with empty or null values

dao/src/main/resources/io/syndesis/dao/demo-data.json, dao/src/main/resources/io/syndesis/dao/deployment.json, dao/src/test/java/io/syndesis/dao/DataManagerTest.java, model/src/main/java/io/syndesis/model/connection/Action.java, model/src/main/java/io/syndesis/model/connection/ActionDefinition.java, model/src/main/java/io/syndesis/model/connection/DataShape.java, rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java, rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java, rest/src/test/java/io/syndesis/rest/v1/handler/IntegrationHandlerTest.java, syndesis-maven-plugin/src/main/java/io/syndesis/maven/GenerateMapperInspectionsMojo.java
This is the first step into aligning the model with the latest version
of the metadata design proposal[1] to test the water and assess any UI
issues that might come of it.
[1] syndesisio/syndesis-project#72
=> chore(metadata): Metadata model changes

dao/src/main/resources/io/syndesis/dao/deployment.json, dao/src/test/java/io/syndesis/dao/DataManagerTest.java, pom.xml, project-generator/src/main/resources/io/syndesis/project/converter/templates/redhat/settings.xml, project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java, project-generator/src/test/resources/io/syndesis/project/converter/redhat/test-settings.xml, project-generator/src/test/resources/io/syndesis/project/converter/test-filter-syndesis.yml, project-generator/src/test/resources/io/syndesis/project/converter/test-integration.json, project-generator/src/test/resources/io/syndesis/project/converter/test-mapper-syndesis.yml, project-generator/src/test/resources/io/syndesis/project/converter/test-pull-push-syndesis.yml, project-generator/src/test/resources/io/syndesis/project/converter/test-syndesis-with-secrets.yml, project-generator/src/test/resources/io/syndesis/project/converter/test-syndesis.yml, runtime/src/main/resources/application.yml
This adds Salesforce and SQL stored procedure connectors needed for TP1.
Removes Salesforce and Twitter actions that do not have an
implementation.
Adds data shape definition to Twitter mention connector.
Fixes #589
=> chore: Define new connectors

controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java, model/src/main/java/io/syndesis/model/WithProperties.java, pom.xml, project-generator/src/main/java/io/syndesis/project/converter/visitor/EndpointStepVisitor.java, project-generator/src/test/resources/io/syndesis/project/converter/test-connectors.json
* Bump Camel to v. 2.20.0 fuse
* Connector are now aliased if they have any component option so the endpoint will look like ``twitter-search-1``
=> GitHub 399 camel configurations

dao/src/main/resources/io/syndesis/dao/deployment.json
Made label a bit clearer. Related to https://github.com/syndesisio/syndesis-ui/issues/970
=> refactor(twitter): Relabeled twitter search action

pom.xml, project-generator/src/test/java/io/syndesis/project/converter/DefaultProjectGeneratorTest.java
Updates connectors to the latest release (0.5.5).
=> chore: update connectors to 0.5.5

controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java
=> fix(openshift): Fix missed openshift oauth token replacement

runtime/src/test/resources/verifier-response-sql-stored-demo-add-metadata.json
This updates the verifier's response for metadata as implemented in
syndesisio/syndesis-verifier#40
=> refactor(metadata): update metadata response from verifier

dao/src/main/resources/io/syndesis/dao/deployment.json
Fixes: syndesisio/syndesis-ui#1031
=> fix(grammar): proper pronoun use

openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
`OpenShiftDeployment`'s `name` property is initialized with
`Integration.name`, within openshift module we should use only the
`sanitizedName` property to interact with OpenShift/k8s API.
Fixes #659
=> fix(openshift): Use sanitized names

dao/src/main/resources/io/syndesis/dao/demo-data.json
=> fix: Use correct connectorId for PostgresDB

.circleci/config.yml, controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java, openshift/src/main/java/io/syndesis/openshift/OpenShiftConfigurationProperties.java, openshift/src/main/java/io/syndesis/openshift/OpenShiftService.java, openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java, openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceNoOp.java, project-generator/src/main/java/io/syndesis/project/converter/DefaultProjectGenerator.java, runtime/src/main/resources/application.yml
Also rearranged order for creation of resources a bit to make it more robuts
=> fix: Missing namespace for builder imagestream

syndesis-builder-image-generator/pom.xml, syndesis-builder-image-generator/src/main/java/io/syndesis/image/Application.java
These failed automatic checks in #688 but that was ignored and manually merged, breaking all future PRs...
=> fix(builder-image-generator): Fix up checks from previous manual merge

pom.xml
This upgrades Camel to the newest version from Fuse early access builds.
=> chore(dependency): upgrade Camel to newest Fuse EA

controllers/src/main/java/io/syndesis/controllers/ControllersConfigurationProperties.java, openshift/src/main/java/io/syndesis/openshift/DeploymentData.java, openshift/src/main/java/io/syndesis/openshift/OpenShiftConfigurationProperties.java, openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
made them configurable, as well as the Maven options now.
=> feat: Add limits to integration runtimes

dao/src/main/java/io/syndesis/dao/validation/UniquePropertyValidator.java, dao/src/test/java/io/syndesis/dao/validation/UniquePropertyValidatorTest.java
Adds an additional check to see if the Integration's current status is
deleted and if so doesn't consider the Integration to clash in the
unique property value.
Fixes #687
=> fix: don't consider Deleted Integrations when checking for Integration name uniqueness

syndesis-builder-image-generator/pom.xml, syndesis-builder-image-generator/src/main/java/io/syndesis/image/Application.java
It would not startup due to missing commons logging lib.
=> fix: builder image generator was a little broken.

openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
As it is seems that Quantity doesn't honor the unit when deserializing.
Fixes #713
=> fix: Add unit directly to amount

pom.xml
That's the last one not triggering https://github.com/openshift/jenkins-sync-plugin/issues/173 and https://github.com/syndesisio/syndesis-rest/issues/747
=> chore: Update to kubernetes-client 2.4.1

pom.xml, syndesis-maven-plugin/pom.xml
Update camel-atlasmap dependency
=> chore: Preps for 1.1.3

controllers/pom.xml, controllers/src/main/java/io/syndesis/controllers/EncryptionComponent.java, controllers/src/main/java/io/syndesis/controllers/integration/IntegrationSupport.java, controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java, controllers/src/main/java/io/syndesis/controllers/integration/online/OnlineHandlerProvider.java, controllers/src/test/java/io/syndesis/controllers/integration/IntegrationSupportTest.java, model/src/main/java/io/syndesis/model/integration/Step.java, rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandler.java, rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionHandler.java, rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java, rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java, rest/src/test/java/io/syndesis/rest/v1/handler/IntegrationHandlerTest.java, rest/src/test/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandlerTest.java, runtime/pom.xml, runtime/src/main/java/io/syndesis/runtime/Application.java, runtime/src/test/resources/application-test.yml
=> feat: Encrypt secrets before storing them in the DB.

rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java, rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationSupportHandler.java, runtime/src/test/java/io/syndesis/runtime/BaseITCase.java, runtime/src/test/java/io/syndesis/runtime/IntegrationsITCase.java
=> feat: Add integration export and import endpoints.

controllers/pom.xml, controllers/src/main/java/io/syndesis/controllers/extension/ExtensionDataProvider.java, controllers/src/test/java/io/syndesis/controllers/extension/ExtensionDataProviderTest.java, dao/src/main/java/io/syndesis/dao/manager/DataManager.java, dao/src/test/java/io/syndesis/dao/DataManagerTest.java
This is needed by artifact generation
=> Fixes #166: Provide way to access active extension data and metadata

controllers/pom.xml, controllers/src/main/java/io/syndesis/controllers/integration/IntegrationSupport.java, controllers/src/main/java/io/syndesis/controllers/integration/online/ActivateHandler.java, controllers/src/main/java/io/syndesis/controllers/integration/online/OnlineHandlerProvider.java, controllers/src/test/java/io/syndesis/controllers/integration/IntegrationSupportTest.java, credential/pom.xml, credential/src/test/java/io/syndesis/credential/CredentialsIntegrationTest.java, dao/pom.xml, dao/src/main/java/io/syndesis/dao/init/ReadApiClientData.java, dao/src/main/java/io/syndesis/dao/manager/DataManager.java, dao/src/main/java/io/syndesis/dao/manager/EncryptionComponent.java, dao/src/main/resources/io/syndesis/dao/deployment.json, dao/src/test/java/io/syndesis/dao/DataManagerTest.java, pom.xml, rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandler.java, rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionHandler.java, rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java, rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java, rest/src/test/java/io/syndesis/rest/v1/handler/IntegrationHandlerTest.java, rest/src/test/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandlerTest.java, syndesis-build-helper-maven-plugin/pom.xml, syndesis-builder-image-generator/src/main/java/io/syndesis/image/Application.java, syndesis-maven-plugin/pom.xml
=> Also encrypt the sampldb connection password.

pom.xml
This reverts commit 185783874fead1d66811796f628f37909b2beb24.
=> fix: #803 Revert "fix: Remove tomcat dependency."

model/src/main/java/io/syndesis/model/ResourceIdentifier.java, model/src/main/java/io/syndesis/model/integration/Step.java, rest/src/main/java/io/syndesis/rest/v1beta1/handler/extension/ExtensionHandler.java, runtime/src/test/java/io/syndesis/runtime/ExtensionsITCase.java
Fixes https://github.com/syndesisio/syndesis-project/issues/167
This adds missing pieces for the API. Pls, let me know if it's ok and/or if something else is missing.
=> Align API to ui needs
